# --- Conexión: La Dorada  ---
[connections.postgresql]
dialect = "postgresql"
host = "172.20.16.72"
port = 5432
database = "UROSOFT"
username = "lector"
password = '*5^Ob4vYoo'

# --- Conexión: Putumayo RECORDAR QUE EN EL CODIGO DE LLAMADO EN LAS FUNCIONES SU USAN LLAVES DE SEGURIDAD---
[connections.putumayo]
dialect = "postgresql"
host = "urosoft.hacputumayo.com.co"
port = 5432
database = "UROSOFT"
username = "lector"
password = "*5^Ob4vYoo"

# --- Conexión: Traumanorte RECORDAR QUE EN EL CODIGO DE LLAMADO EN LAS FUNCIONES SU USAN LLAVES DE SEGURIDAD---
[connections.traumanorte]
dialect = "postgresql"
host = "urosoft.traumanorte.com.co"
port = 5432
database = "UROSOFT_TN"
username = "lector"
password = "*5^Ob4vYoo"

# --- Conexión: UCM RECORDAR QUE EN EL CODIGO DE LLAMADO EN LAS FUNCIONES SU USAN LLAVES DE SEGURIDAD---
[connections.ucm]
dialect = "postgresql"
host = "urosoft.clinicalamagdalena.com"
port = 5432
database = "UROSOFT_MAGDALENA"
username = "lector"
password = "*5^Ob4vYoo"
